version: '3.7'

volumes:
  # Shared with your geoserver, if you ave one!
  geowebcache_data:
    name: geowebcache_data

networks:
  # This is a network we share with our reverse proxy
  proxy:
    name: proxy
    # Won't be created or destroyed with docker-compose up|down
    external: true

services:
  geowebcache:
    container_name: geowebcache
    image: wildsong/geowebcache:latest
    environment:
      ENABLE_JSONP: "true"
      GEOWEBCACHE_DATA_DIR: /geowebcache
    networks:
      - proxy
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - geowebcache_data:/geowebcache
    labels:
      caddy: geowebcache.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls.protocols: "tls1.3"
      caddy.tls.dns: "cloudflare ${CLOUDFLARE_API_TOKEN}"
    restart: unless-stopped
